### ISSUE TITLE
Getting "An unexpected error happened" while accessing the data source

### ISSUE THREAD

**Issue by JyotiPMallick** [grafana/github-datasource#312]
I am trying to use the Github Grafana Datasource for my project, I am using grafana version 9.0.1.

Steps I used : 

1. Login to grafana and navigate to plugin manager.
2. Installed grafana-github plugin 
![image](https://github.com/grafana/github-datasource/assets/165989474/9dca725e-da20-48c5-94ab-88149abaeea4)
3. Navigate to data source section and select the github data source I am getting, 
![image](https://github.com/grafana/github-datasource/assets/165989474/d989a0a7-fbd7-4596-b259-3fb469dc0cf3)

Error Details: 

```
An unexpected error happened
DetailsError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at div
    at div
    at h (http://localhost:3000/public/build/2809.962b345825f22166a490.js:446:27)
    at div
    at div
    at X (http://localhost:3000/public/plugins/grafana-github-datasource/module.js:1:11717)
    at le (http://localhost:3000/public/plugins/grafana-github-datasource/module.js:1:13065)
    at eval (http://localhost:3000/public/plugins/grafana-github-datasource/module.js:16:1582)
    at div
    at I (http://localhost:3000/public/build/DataSourceSettingsPage.c968388d22c7258c1511.js:1:3183)
    at form
    at div
    at div
    at m.Contents (http://localhost:3000/public/build/2809.962b345825f22166a490.js:5510:893)
    at div
    at div
    at div
    at t (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:777259)
    at c (http://localhost:3000/public/build/2809.962b345825f22166a490.js:314:168)
    at div
    at m (http://localhost:3000/public/build/2809.962b345825f22166a490.js:5510:243)
    at A (http://localhost:3000/public/build/DataSourceSettingsPage.c968388d22c7258c1511.js:1:5187)
    at g (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:1096373)
    at n (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:1042703)
    at Do (http://localhost:3000/public/build/2809.962b345825f22166a490.js:8261:23560)
    at t (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:1111691)
    at t (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:1113712)
    at main
    at t (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:1108309)
    at div
    at us (http://localhost:3000/public/build/2809.962b345825f22166a490.js:2569:1029)
    at t.KBarProvider (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:358763)
    at c (http://localhost:3000/public/build/2809.962b345825f22166a490.js:5853:27780)
    at Bl (http://localhost:3000/public/build/2809.962b345825f22166a490.js:3111:467)
    at zl (http://localhost:3000/public/build/2809.962b345825f22166a490.js:3111:1023)
    at y (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:141237)
    at Oo (http://localhost:3000/public/build/2809.962b345825f22166a490.js:8261:23089)
    at l (http://localhost:3000/public/build/4902.331bf177ac0b86d7f476.js:2:1094418)
    at tl (http://localhost:3000/public/build/2809.962b345825f22166a490.js:8274:115)
```

**Comment by zoltanbedi** [comment]
Hi @JyotiPMallick,

Thanks for opening this issue for us. Please update your grafana instance to at least 9.1.0 as the current version of the plugin is not compatible with that old version.

**Comment by JyotiPMallick** [comment]
@zoltanbedi thank you so much, I updated and it work like a charm. But don't you think the message is misleading. It should be proper ?
